import type { Metadata, Viewport } from "next";
import "./globals.css";

const geistSans = {
  variable: "font-sans",
};

const geistMono = {
  variable: "font-mono",
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

import { AuthProvider } from "@/context/AuthContext";
import { ThemeProvider } from "@/context/ThemeContext";
import { SocialProvider } from "@/context/SocialContext";
import NavigationWrapper from "@/components/navigation/NavigationWrapper";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[var(--background)] text-[var(--foreground)] overflow-x-hidden`}
      >
        <AuthProvider>
          <SocialProvider>
            <ThemeProvider>
              <NavigationWrapper>
                {children}
              </NavigationWrapper>
            </ThemeProvider>
          </SocialProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
