const ragService = require('./ai/ragService');

const summarizeDocument = async (document_id) => {
  try {
    const result = await ragService.summarize(document_id);
    const aiResponse = {
      abstract: result.answer.split('\n')[0] || 'Summary generated by ResearchReel AI.',
      key_points: result.answer.split('\n').filter(l => l.trim().startsWith('-') || l.trim().match(/^\d\./)).slice(0, 3),
      video_script: result.answer.includes('Script') ? result.answer.split('Script')[1] : 'No script generated.'
    };
    return aiResponse;
  } catch (error) {
    console.warn(`[AI Service] RAG summarization failed for doc ${document_id}, returning graceful fallback:`, error.message);
    return {
      abstract: 'Abstract summary is temporarily unavailable as the AI service is currently offline. Please try again later.',
      key_points: [
        'AI Summarization service is offline',
        'Could not generate automated key highlights',
        'Please review the full PDF directly'
      ],
      video_script: 'Hey researchers! Unfortunately our RAG service is temporarily offline, so we could not generate a video script hook for this paper. Feel free to upload your own or try again shortly!'
    };
  }
};

const askGemini = async ({ document_id, question, history }) => {
  const result = await ragService.query(question, document_id ? [document_id] : []);
  return {
    answer: result.answer,
    citations: result.chunks.map(chunk => ({
      page: chunk.metadata.page || 'N/A',
      section: chunk.metadata.section || 'General',
      text: chunk.content.substring(0, 150) + '...'
    })),
    latency: result.latency
  };
};

const getRecommendations = async ({ user_id }) => {
  return [
    { id: 'rec1', title: 'Scaleable Logical Inference in GNNs', similarity: 0.94 },
    { id: 'rec2', title: 'Recent Advances in OOD Generalization', similarity: 0.88 }
  ];
};

module.exports = {
  summarizeDocument,
  askGemini,
  getRecommendations
};
